### ISSUE TITLE
Cancel Request does not stop running analysis

### ISSUE THREAD

**Issue by kmindi** [CROSSINGTUD/CogniCrypt#201]
**Describe the bug**
After I clicked the stop button on the background process of CogniCrypt I expected it to stop the analysis, but the analysis continued to run.

It may be important to note that my eclipse project has 100 packages where each has a main method.

**Comment by kruegers** [comment]
@kmindi The problem here is the process of how cancelling in Eclipse plugins is being [implemented](https://kaloyanraev.blogspot.com/2016/03/why-does-canceling-operations-in.html). That said, I have made some changes to how CogniCrypt handles canceling to make it more effective. Long story short, please update CogniCrypt from the update site and check out whether it works as expected.

**Comment by kruegers** [comment]
Thanks. Then, I'm closing this issue now.
