### ISSUE TITLE
Unintended blank window on wizard invocation

### ISSUE THREAD

**Issue by rajiv-thorat** [CROSSINGTUD/CogniCrypt#47]
#### Prerequisites
* **Eclipse Version:**  Neon.3 Release (4.6.3)`
* **Operating system:** Linux Mint 18.1
* **Java runtime used to run eclipse:** 1.8.0_131
* **Git branch/Commit-ID:**  master/96111043bb7a87018ecf80053cf7f46a76a4f34c

### Issue description
On invoking the wizard a blank window is displayed in the background. Appears to be unintended. 

![screenshot from 2017-07-12 01-02-58](https://user-images.githubusercontent.com/1528669/28095213-6ec74e1c-66a1-11e7-8ba1-852d00390ac7.png)

Closing the wizard does not terminate said window.

![screenshot from 2017-07-12 01-04-01](https://user-images.githubusercontent.com/1528669/28095212-6ec6e3dc-66a1-11e7-954f-21901643cb81.png)

**Comment by kruegers** [comment]
@rajiv-thorat & @abirke : Was that still an issue the last time you used CogniCrypt?

@AndreSonntag, @adnan904 & @enriozuni: Does any of you run a linux machine or has a linux VM setup? Please answer here and do *not* wait til the meeting on Wednesday.

**Comment by enriozuni** [comment]
No I don't run a Linux VM or setup



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by abirke** [comment]
I just reproduced the issue using

* ubuntu 16.04 LTS
* java-8-openjdk-amd64 (from aptitude repositories)
* Eclipse IDE for Java Developers Photon Release (4.8.0)

![screenshot from 2018-06-29 13-29-11](https://user-images.githubusercontent.com/29310187/42090151-819a038a-7ba0-11e8-8f12-50d0fb03c301.png)

Please note that (as previously), I didn't manage to start eclipse with GTK3 activated, which is why I used
```
SWT_GTK3=0 ~/bin/eclipse/java-photon/eclipse/eclipse
```
to start eclipse.

Admittedly, I didn't spend a lot of time on the GTK3 issue as Linux didn't seem to be a target platform at that time. So it might be something worth looking into in the context of this issue. Let me know if I can help.

**Comment by adnan904** [comment]
I also faced the same issue.
- Ubuntu 18.04 LTS
- Java 10 Oracle
- Eclipse Photon 4.8.0

![screenshot from 2018-06-30 11-29-03](https://user-images.githubusercontent.com/34026698/42123936-a1531d8c-7c5a-11e8-955c-82b1058e8918.png)

**Comment by kruegers** [comment]
@adnan904 Great. Please read through the rest of the thread and work to resolve the issue. Running eclipse with GTK3 enabled as @abirke suggested seems to be a good start. If you need help, feel free to take @abirke up on his offer.
